[project]
name = "pajbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "apscheduler>=3.10.4",
    "autobahn>=24.4.2",
    "beautifulsoup4>=4.12.3",
    "colorama>=0.4.6",
    "irc>=20.5.0",
    "markdown>=3.7",
    "markupsafe>=2.1.5",
    "marshmallow-dataclass>=8.7.0",
    "marshmallow>=3.22.0",
    "psycopg2>=2.9.9",
    "pyopenssl>=24.2.1",
    "pytimeparse>=1.1.8",
    "rapidfuzz>=3.9.6",
    "redis>=5.0.8",
    "regex>=2024.7.24",
    "requests>=2.32.3",
    "retry>=0.9.2",
    "service-identity>=24.1.0",
    "sqlalchemy-utc>=0.14.0",
    "sqlalchemy>=2.0.32",
    "twisted>=24.7.0",
    "unidecode>=1.3.8",
    "urlextract>=1.9.0",
]

[tool.uv]
dev-dependencies = [
    "black>=24.8.0",
    "flake8>=7.1.1",
    "isort>=5.13.2",
    "mypy>=1.11.2",
    "pytest>=8.3.2",
    "ruff>=0.6.9",
    "types-beautifulsoup4>=4.12.0.20240907",
    "types-colorama>=0.4.15.20240311",
    "types-markdown>=3.7.0.20240822",
    "types-psycopg2",
    "types-pytz>=2.32.0.20240914",
    "types-requests",
    "types-retry",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
addopts = [
    "-vvv",
]
pythonpath = "src"

[tool.ruff.lint]
select = [
    "E",
    "F",
    "W",
    "C90",
]
ignore = [
#     "E123",
#     "E126",
#     "E127",
#     "E128",
     "E501", # Line too long
     "C901", # Too complex
#     "E131",
     "E721", # use isinstance or is/is not. REMOVE THIS SOON xd
     "E722", # bare except
#     "Q003",
#     "Q000",
#     "W503",
#     "E203",
#     "E704",
]

[[tool.mypy.overrides]]
module = "irc.*"
ignore_missing_imports = true

[tool.uv.workspace]
members = ["pajbot", "bot", "web"]

[tool.uv.sources]
pajbot = { workspace = true }
