---
name: Python 4HEad

on:
  push:
    branches:
      - master
  pull_request:

env:
  SKIP_PYENV: "1"

jobs:
  test:
    name: "Test ubuntu-latest, Python ${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - name: Set up Python
        run: uv python install ${{ matrix.python-version }}
      - name: Install project
        run: uv sync --all-extras --dev

      - name: Run pajbot lib tests
        run: uv run pytest

  check_format:
    name: "Check format ubuntu-latest, Python ${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - name: Set up Python
        run: uv python install ${{ matrix.python-version }}
      - name: Install project
        run: uv sync --all-extras --dev

      - name: Check code style
        run: ./scripts/reformat.sh --check
